name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Configure
      run: cmake .

    - name: Build
      run: make -j4
    - name: List contents of build output (recursive)
      run: |
        echo "== Root =="
        ls -la
        echo "== EtcTool =="
        ls -la EtcTool || true
        echo "== EtcTool/Debug =="
        ls -la EtcTool/Debug || true
    - name: Find all generated files
      run: |
        echo "Searching for built binary..."
        find . -type f -name 'EtcTool*' -exec ls -l {} \;
    - name: Upload to artifacts
      uses: actions/upload-artifact@v4
      with:
          name: mac-build
          path: EtcTool\Debug\EtcTool
