name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Configure
      run: cmake .

    - name: Build
      run: make -j4
    - name: Upload to artifacts
      uses: actions/upload-artifact@v4
      with:
          name: mac-build
          path: EtcTool\Debug\EtcTool
